spring.application.name=FoodieFix
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.user.name=yuva
spring.security.user.password=1234

jwt.secret=yegvfibvjdbvcsetd36478guirevowei
jwt.exp=86400000

server.port=8080
